### PR TITLE
fix: do not insert nonexistent experts into the `pending_egress`

### LINKED ISSUE #60: Failed requests not removed from queue causing persistent errors
## Issue
When a request encounters an error (e.g., requesting a non-existent expert), it gets raised at [this location](https://github.com/expert-kit/expert-kit/blob/dev/ek-computation/src/controller/executor.rs#L158) but the request is not removed from the queue.

## Problem
This causes every subsequent request to fail at the same location with the same error.

## Expected
Failed requests should be removed from the queue to prevent blocking future requests.

### PR DESCRIPTION
**Pull request by Coekjan**
This PR fixes #60 .

Change `break_down_to_egress` (private function) into an async function.

### CODE REVIEW

**Comment by Coekjan** [comment]
@CNLHC please review, looking forward to your reply.

File: ek-computation/src/controller/executor.rs [hunk 1]
```diff
@@ -295,12 +295,23 @@ impl NaiveExecutor {
...
-    fn break_down_to_egress(&mut self, req: &v1::ForwardReq, req_id: ReqId) {
+    async fn break_down_to_egress(&mut self, req: &v1::ForwardReq, req_id: ReqId) {
         for (idx, seq) in req.sequences.iter().enumerate() {
             // update pending_seq
             let seq_gid = self.add_seq(req_id, idx as LocalSeqIdx);
             // update pending_req
             for (idx, expert) in seq.experts.iter().enumerate() {
+                if self
+                    .registry
+                    .lock()
```
Comment (CNLHC) [inline ek-computation/src/controller/executor.rs]: Acquire a lock here will introduce too much overhead. Expert existence check should not be placed here.

Comment (CNLHC) [reply ek-computation/src/controller/executor.rs]: Besides, we should avoid using async function if possible.

Comment (Coekjan) [reply ek-computation/src/controller/executor.rs]: Thanks for your comments. What about using a rwlock (to reduce overhead)? Which place to check existency you think is better?

Comment (CNLHC) [reply ek-computation/src/controller/executor.rs]: My opinion is avoiding check here. If non-existent expert is used, it must be an implementation or configuration error which can not be recovered, so let it fail is better.

Comment (Coekjan) [reply ek-computation/src/controller/executor.rs]: So I think we can simply let rust panic when we meet these nonexistent experts.

Comment (CNLHC) [reply ek-computation/src/controller/executor.rs]: No need to panic here cause we can not assert the error is in the controller binary. Based on my experience, this error is more likely caused by the integration plugin.

Comment (Coekjan) [reply ek-computation/src/controller/executor.rs]: The issue states when nonexistent experts detected,`pending_egress` always contains them (instead of removing them) and leads to incessive annoying errors in log. Maybe we can remove them [here](https://github.com/expert-kit/expert-kit/blob/647a8e56133d86cbf2c3aaa120ffb34797e2d76c/ek-computation/src/controller/executor.rs#L159), like:

```rust
let Ok(channel) = self.registry.lock().await.select(expert_id).await else {
    // remove the expert_id from pending_egress
    // and log::warn! or log::error!
    continue; // or return error to the caller?
};
```

**Comment by Coekjan** [comment]
@EthanO-O Please review
